### ISSUE TITLE
nymea network on bananapi (ubuntu server)

### ISSUE THREAD

**Issue by legnaro** [nymea/nymea-networkmanager#23]
Hi,

I'm big fan of this project and I have been used berrylan with raspberry zero (kali linux) with no errors. Now I trying to use in BananaPi M2 zero with UbuntuServer. I've got a message:  

pi@bpi-iot-ros-ai:/home$ sudo nymea-networkmanager --mode always -d
nymea-networkmanager: /usr/lib/arm-linux-gnueabihf/libQt5DBus.so.5: version `Qt_5' not found (required by nymea-networkmanager)
nymea-networkmanager: /usr/lib/arm-linux-gnueabihf/libQt5Core.so.5: version `Qt_5' not found (required by nymea-networkmanager)
nymea-networkmanager: /usr/lib/arm-linux-gnueabihf/libQt5DBus.so.5: version `Qt_5' not found (required by /usr/lib/arm-linux-gnueabihf/libnymea-networkmanager.so.1)
nymea-networkmanager: /usr/lib/arm-linux-gnueabihf/libQt5Core.so.5: version `Qt_5' not found (required by /usr/lib/arm-linux-gnueabihf/libnymea-networkmanager.so.1)
nymea-networkmanager: /usr/lib/arm-linux-gnueabihf/libQt5Core.so.5: version `Qt_5' not found (required by /usr/lib/arm-linux-gnueabihf/libnymea-gpio.so.1)
pi@bpi-iot-ros-ai:/home$ 

If I try for another way like compile the project, th system return this message:
Project ERROR: nymea-networkmanager development package not found

Apparently is posible to run nymea-networkmanager in this hardware, but I don't know how the best way to fix these issue. 

tks

**Comment by mzanetti** [comment]
Hmm... not really sure why Qt5 ABI on the banana Pi seems to not match. Did you perhaps use the "armel" builds of nymea-networkmanager but you'd need the "armhf" ones instead? If you've used the "raspbian" section of the repo, try using the "main" section instead.


As for the compile issues: nymea-networkmanager has been split into 2 repos recently: libnymea-networkmanager and nymea-networkmanager. You'd need to build the lib before the main application.

And, please use the forum at forum.nymea.io/berrylan for this sort of questions as it isn't a bug report. Thanks :)
