### ISSUE TITLE
symbol lookup error: undefined symbol: _ZN15BluetoothServer14runningChangedERKb

### ISSUE THREAD

**Issue by limkevinkuan** [nymea/nymea-networkmanager#28]
Device: Raspberry Pi 3B+
OS: Raspbian Buster Lite

Upgraded raspberrypi-firmware, rpi-eeprom etc. as well as nymea-networkmanager with `sudo apt dist-upgrade`.
Now running nymea-networkmanager fails with:
`nymea-networkmanager: symbol lookup error: nymea-networkmanager: undefined symbol: _ZN15BluetoothServer14runningChangedERKb`

Reinstalling according to the instructions at http://www.berrylan.org/faq.html#5 didn't fix it.

**Comment by t-mon** [comment]
Hello! Could you sent me please the output of 
`apt policy nymea-networkmanager`
and
`apt policy libnymea-networkmanager`

undefined symbol means a function is not available in the library, so maybe this is a library daemon mismach.

**Comment by limkevinkuan** [comment]
Indeed, apt is confused by the version number of libnymea-networkmanager.
```
$ apt policy nymea-networkmanager 
nymea-networkmanager:
  Installed: 0.5.1+202001231339~stretch1
  Candidate: 0.5.1+202001231339~stretch1
  Version table:
 *** 0.5.1+202001231339~stretch1 500
        500 http://repository.nymea.io stretch/main armhf Packages
        100 /var/lib/dpkg/status
     0.3.2 500
        500 http://repository.nymea.io stretch/raspbian armhf Packages

$ apt policy libnymea-networkmanager 
libnymea-networkmanager:
  Installed: 0.3.2
  Candidate: 0.3.2
  Version table:
 *** 0.3.2 500
        500 http://repository.nymea.io stretch/raspbian armhf Packages
        100 /var/lib/dpkg/status
     0.2.3+202002232338~stretch1 500
        500 http://repository.nymea.io stretch/main armhf Packages
```

**Comment by t-mon** [comment]
As you already noticed, there is a general `stretch/main` repository working on all `armhf` (which can be removed on the Raspberry Pi) and a `stretch/raspbian` section which is a special compiled repository for the Raspberry Pi allowing you to install this on Raspberry Pi 1, ZeroW, 2, 3 and 4.

Your `/etc/apt/sources.list.d/nymea.list` should look like this:

    deb http://repository.nymea.io stretch raspbian

Please not if you switch in the future to debian buster, the section is gonna called `deb http://repository.nymea.io buster rpi`

Glad we figured it out :)

**Comment by t-mon** [comment]
Oh, I just noticed that the stretch raspbian section is outdated. So if you are running on a Raspberry Pi 2,3 or 4 you should probably go with the main section, since we build `rpi` packages only for buster. 

So for stretch your `nymea.list` file should look like this:

    deb http://repository.nymea.io stretch raspbian

Sorry for the confusion.

**Comment by limkevinkuan** [comment]
Thanks. I do hope for a lite build sometime without dependencies on GUI libraries.

**Comment by mzanetti** [comment]
Hmm, what GUI libraries are you referring to?
