### ISSUE TITLE
Repo problems

### ISSUE THREAD

**Issue by rijotech** [nymea/nymea-networkmanager#31]
Trying to install nginx and other software in getting the following error from berrylan image.
`pi@raspberrypi:~ $ sudo apt install lighttpd
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libfam0 libmariadb3 lighttpd-modules-ldap lighttpd-modules-mysql mariadb-common mysql-common
  spawn-fcgi
Suggested packages:
  fam rrdtool php-cgi apache2-utils lighttpd-doc
The following NEW packages will be installed:
  libfam0 libmariadb3 lighttpd lighttpd-modules-ldap lighttpd-modules-mysql mariadb-common
  mysql-common spawn-fcgi
0 upgraded, 8 newly installed, 0 to remove and 0 not upgraded.
Need to get 546 kB of archives.
After this operation, 1,663 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://raspbian.mirror.constant.com/raspbian buster/main armhf libfam0 armhf 2.7.0-17.3 [24.6 kB]
Get:2 http://raspbian.mirror.constant.com/raspbian buster/main armhf mysql-common all 5.8+1.0.5 [7,324 B]
Get:3 http://raspbian.mirror.constant.com/raspbian buster/main armhf mariadb-common all 1:10.3.22-0+deb10u1 [31.9 kB]
Get:4 http://raspbian.mirror.constant.com/raspbian buster/main armhf libmariadb3 armhf 1:10.3.22-0+deb10u1 [158 kB]
Get:5 http://raspbian.mirror.constant.com/raspbian buster/main armhf lighttpd armhf 1.4.53-4 [292 kB]
Get:6 http://raspbian.mirror.constant.com/raspbian buster/main armhf lighttpd-modules-ldap armhf 1.4.53-4 [8,832 B]
Get:7 http://raspbian.mirror.constant.com/raspbian buster/main armhf lighttpd-modules-mysql armhf 1.4.53-4 [8,972 B]
Get:8 http://raspbian-us.ngc292.space/raspbian buster/main armhf spawn-fcgi armhf 1.6.4-2 [13.9 kB]
Err:8 http://raspbian-us.ngc292.space/raspbian buster/main armhf spawn-fcgi armhf 1.6.4-2
  File has unexpected size (16384 != 13928). Mirror sync in progress? [IP: 198.211.116.210 443]
Fetched 532 kB in 7s (80.8 kB/s)
E: Failed to fetch https://113store.cr/es/  File has unexpected size (16384 != 13928). Mirror sync in progress? [IP: 198.211.116.210 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
`
I have done sudo apt update, upgrade and I'm still getting the same error.

**Comment by rijotech** [comment]
Never mind not related to the project but the OS.

**Comment by mzanetti** [comment]
Right... you just happened to apt-get update in the middle of a repo sync... Normally that should fix itself within a few minutes.
