### ISSUE TITLE
Custom native app to interact with nymea

### ISSUE THREAD

**Issue by jaumard** [nymea/nymea-networkmanager#34]
Hello !! 

I'm searching for a way to setup the WiFi via BT on my raspberry pi home automation system (https://github.com/mylisabox) and find Nymea/berrylan (https://github.com/nymea/berrylan). 

Look pretty interesting ! But I'm a bit lost ^^ so from what I understand I have to install nymea-networkmanager on my PI and that's basically it for server side. 

I can't use `berrylan` because I already have my own mobile app and want it integrated to it, so my idea was to look how you did on native side of the app but it's all QT code lol which I don't know. So I tried to look at the BT protocole you have here but it is not clear to me too :( 

So my main question is what are the minimal steps I have to do to talk with nymea in bluetooth. Because I only need to setup the WiFi if not already setup and that's it and look like nymea is doing more. Or is there any example of native iOS / Android interaction with nymea I could look

**Comment by Boernsman** [comment]
Hi,
the nymea-networkmanager works standalone, you won't need nymea installed,
though nymea could be of interest for your project (java-script plug-ins are supported as well).

What is not clear on the BT protocol? 
@rhythm-section maybe you can give a helping hand

**Comment by jaumard** [comment]
Ok look like your documentation is super clear, I just didn't had enough knowledge about BLE connection ^^
I was able to connect to nymea and retrieve the services and characteristics. 

But when I tried to call `getNetworks`  I get the response `{"c":0,"p":[],"r":0}`, but when I run `iwlist wlan0 scan` I'm getting 
```
wlan0     Scan completed :
          Cell 01 - Address: 24:7F:20:C5:C5:FC
                    Channel:11
                    Frequency:2.462 GHz (Channel 11)
                    Quality=58/70  Signal level=-52 dBm  
                    Encryption key:on
                    ESSID:"BibouBox"
                    Bit Rates:1 Mb/s; 2 Mb/s; 5.5 Mb/s; 11 Mb/s; 6 Mb/s
                              9 Mb/s; 12 Mb/s; 18 Mb/s
                    Bit Rates:24 Mb/s; 36 Mb/s; 48 Mb/s; 54 Mb/s
                    Mode:Master
                    Extra:tsf=0000000000000000
                    Extra: Last beacon: 50ms ago
                    IE: Unknown: 00084269626F75426F78
                    IE: Unknown: 010882848B960C121824
                    IE: Unknown: 03010B
                    IE: Unknown: 050402030000
                    IE: Unknown: 0706465220010D14
                    IE: Unknown: 2A0100
                    IE: Unknown: 32043048606C
                    IE: Unknown: 2D1AAD011BFFFF0000000000000000000000000000000406E4A70C00
                    IE: Unknown: 3D160B080400000000000000000000000000000000000000
                    IE: Unknown: DD180050F2020101850003A4000027A4000042435E0062322F00
                    IE: Unknown: DD0900037F01010000FF7F
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (2) : CCMP TKIP
                        Authentication Suites (1) : PSK
                    IE: WPA Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (2) : CCMP TKIP
                        Authentication Suites (1) : PSK
```

So there is a a WiFi available but none are returned by nymea :/ did I miss something?

**Comment by jaumard** [comment]
I'm running nymea on a raspberry pi 3

**Comment by mzanetti** [comment]
Can you try to explicitly call "Scan" before "GetNetworks"?

**Comment by jaumard** [comment]
I just tried but no luck :( 
But on raspberry pi side when I call Scan I can see `NetworkManager: Scan error: "org.freedesktop.NetworkManager.Device.NotAllowed" "Scanning not allowed while unavailable or activating"` not sure what I can do about that

**Comment by mzanetti** [comment]
Can you paste the whole log from startup to reproducing the issue please.

**Comment by jaumard** [comment]
Sure here is my logs:
```
 nymea-networkmanager -m always
 I | Application: Using configuration file from: "/etc/nymea/nymea-networkmanager.conf"
 I | Application: =====================================
 I | Application: Starting nymea-networkmanager "0.3.0"
 I | Application: =====================================
 I | Application: Advertising name: "mylisabox"
 I | Application: Platform name: "mylisabox"
 I | Application: Mode: Core::Mode(ModeAlways)
 I | Application: Timeout: 60
 W | NymeaService: Invalid D-Bus HardwareManager interface.
 W | NymeaService: Could not init nymea D-Bus services
 I | Application: NetworkManager::NetworkManagerState(NetworkManagerStateConnectedGlobal)
 I | Application: Networkmanager networking is now enabled
 I | Application: Networkmanager wireless networking is now enabled
 I | Application: Init is running
 I | Application: Post run service
 I | Application: Start the bluetooth service because of "always" mode.
 I | Application: Start service
 W | NymeaService: Could not enable/disable bluetooth hardware resource. D-Bus interface not available.
 I | Application: Start bluetooth service
 I | Application: Bluetooth server started
 I | Application: Bluetooth client connected
 W | qt.bluetooth.bluez: sending error response; request: 16 handle: 51 code: 10
 W | qt.bluetooth.bluez: sending error response; request: 8 handle: 1 code: 10
 W | qt.bluetooth.bluez: sending error response; request: 8 handle: 11 code: 10
 W | qt.bluetooth.bluez: sending error response; request: 8 handle: 12 code: 10
 W | qt.bluetooth.bluez: sending error response; request: 8 handle: 20 code: 10
 W | qt.bluetooth.bluez: sending error response; request: 8 handle: 21 code: 10
 W | qt.bluetooth.bluez: sending error response; request: 8 handle: 23 code: 10
 W | qt.bluetooth.bluez: sending error response; request: 8 handle: 24 code: 10
 W | qt.bluetooth.bluez: sending error response; request: 8 handle: 37 code: 10
 W | qt.bluetooth.bluez: sending error response; request: 8 handle: 39 code: 10
 W | qt.bluetooth.bluez: sending error response; request: 8 handle: 49 code: 10
 W | NetworkManager: Scan error: "org.freedesktop.NetworkManager.Device.NotAllowed" "Scanning not allowed while unavailable or activating"

```

**Comment by jaumard** [comment]
I've tried to build my own pi-gen version based on yours, but I encounter some issues

I have getNetworks working but one I tried to connect to the network I'm getting `{c: 1, r: 7}` but not sure to understand 7 error mean from the doc and mostly how to fix it ^^

**Comment by mzanetti** [comment]
Hmm... Error 7 seems to be "unknown error". I'm sure in that case the logs of nymea-networkmanager print something...

Here's a hint: if you configure nymea-networkmanager to be enabled always, you can connect the pi to ethernet and SSH into it and then use journalctl to live-monitor the logs while doing the bluetooth setup.

**Comment by jaumard** [comment]
I've checked the log nothing's popup but as I shows the json command I was able to find out the error, I got a bug in my send request and a character wasn't sent on ssid and password. So ssid wasn't existing as a character was missing. Once I fix that bug everything is ok now. Maybe adding another error like 8: "Network info wrong"  would be helpful (even for people to show right error messages) because I tried with a good ssid but wrong password I also get a 7. 

For me 7 is "An unknow error as occured" for error message dialog. I would like to be able to say "Network unreachable please check your password"

**Comment by mzanetti** [comment]
Fair point.

Glad you got it working.

**Comment by jaumard** [comment]
So I've made a Flutter package to interact with nymea network manager. So far so good :) thanks a lot for your help and for this!

https://github.com/mylisabox/nymea_network_manager

**Comment by jaumard** [comment]
Hello guys!

I'm back to you because for some reason nymea doesn't start the bluetooth server when the PI boots, if I launch it manually no problem. But is it normal it doesn't start with the system ? Anything I should do ? Or any logs I can look at to search for errors ?

**Comment by jaumard** [comment]
Look like on PI 3 it start on boot, but PI 4 it doesn't :( based on the image generated with the pi-gen

**Comment by mzanetti** [comment]
Hi @jaumard 

wow, that's pretty cool. 

For the problem you're facing. Perhaps you can try to check nymea-networkmanagers logs. Right now I'm not sure why it wouldn't work for you.
When it doesn't work, please fetch the logs from `sudo journalctl -u nymea-networkmanager` from the boot until the end and post it here.
