### ISSUE TITLE
issue installing berrylan on arm64

### ISSUE THREAD

**Issue by ericmigi** [nymea/nymea-networkmanager#35]
I tried following the berrylan install instructions on Raspberry Pi OS 64bit but ran into this issue

```
The following packages have unmet dependencies:
 nymea-networkmanager:armhf : Depends: libqt5network5:armhf but it is not going to be installed
                              Depends: libqt5bluetooth5:armhf but it is not going to be installed
                              Depends: network-manager:armhf but it is not going to be installed
                              Depends: libnymea-networkmanager:armhf but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Any suggestions? Thanks for making berrylan, it's been super useful!

**Comment by mzanetti** [comment]
You're trying to install armhf packages on arm64... Our rpi specific repository does not host arm64 packages. You can try using our plain debian buster arm64 repo instead:

`deb http://repository.nymea.io buster main`

**Comment by ericmigi** [comment]
wow that's perfect, thanks!
