### ISSUE TITLE
Impossible to find the bluetooth device - Pi Zero

### ISSUE THREAD

**Issue by maxencekyz** [nymea/nymea-networkmanager#49]
Hello, @mzanetti @nymea-jenkins 

I tried many times but nothing works.
When I launch the Android App, it's always written "searching for your raspberry pi".
The network manager is in "offline" mode. And I see, it is activated when I turn on my Raspberry Pi Zero.

I would like to uninstall it properly and re-install it again. ( i hope it will solve the problem )
How can I do that ?

Thanks per advance,

**Comment by t-mon** [comment]
Hello @maxencekyz,

you can re-install the nymea-networkmanager using following commands

    sudo apt purge nymea-networkmanager
    sudo apt autoremove
    sudo apt clean
    sudo apt update && sudo apt install nymea-networkmanager
    
More interesting would be, why your phone does not find the bluetooth server.

Can you post following information, maybe that gives us a hint:

> Note: Please make sure you don't share passwords with the logs

    systemctl restart nymea-networkmanager && journalct -f -u nymea-networkmanager
    
And:

    apt policy nymea-networkmanager

**Comment by maxencekyz** [comment]
Thanks for your quick reply @t-mon !

So I follow your tips and re-install it. I changed the module mode to "always", so it's more convenient for me with the App.
I've currently the same problem, no BT WLAN SETUP appears on my phone. Still searching...

When i send `apt policy nymea-networkmanager` , this is what I have :

![image](https://user-images.githubusercontent.com/80335419/112750354-712df300-8fc8-11eb-8bb0-21cf3c77d8f7.png)

For `systemctl restart nymea-networkmanager && journalct -f -u nymea-networkmanager` , this is what I have :

`-bash: journalct : command not found`

Any solution ?

**Comment by mzanetti** [comment]
There's a typo in the command, should be `journalctl`, not `journalct`

**Comment by maxencekyz** [comment]
Thanks @mzanetti
So as I said, I changed the module mode to "always", so it's more convenient for me with the App.
At the moment, i'm connected to my internet "Livebox-9790" but i should be able to see the BL WLAN setup on my app at anytime due to the "always" mode.

For `systemctl restart nymea-networkmanager && journalctl -f -u nymea-networkmanager `, this is what I have :

> -- Logs begin at Sun 2021-03-28 19:17:02 CEST. --
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1523]:  I | Application: Shutting down bluetooth service
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1523]:  I | NetworkManagerBluetoothServer: Destroy bluetooth server.
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1523]:  I | NetworkManagerBluetoothServer: Controller state disonnected.
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1523]:  I | NetworkManagerBluetoothServer: Set running false
mars 29 11:08:34 RaspberryPi systemd[1]: Stopping Daemon for nymea to configure wifi network using a Bluetooth LE connection...
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1523]:  I | Application: Shutting down network-manager service
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1523]:  I | NetworkManager: Destroy network manager.
mars 29 11:08:34 RaspberryPi systemd[1]: nymea-networkmanager.service: Succeeded.
mars 29 11:08:34 RaspberryPi systemd[1]: Stopped Daemon for nymea to configure wifi network using a Bluetooth LE connection.
mars 29 11:08:34 RaspberryPi systemd[1]: Started Daemon for nymea to configure wifi network using a Bluetooth LE connection.
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1537]:  I | Application: Using configuration file from: "/etc/nymea/nymea-networkmanager.conf"
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1537]:  I | Application: =====================================
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1537]:  I | Application: Starting nymea-networkmanager "0.5.5+202011171557~buster+rpi1"
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1537]:  I | Application: =====================================
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1537]:  I | Application: Advertising name: "BT WLAN setup"
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1537]:  I | Application: Platform name: "nymea-box"
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1537]:  I | Application: Mode: Core::ModeAlways
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1537]:  I | Application: Timeout: 60
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1537]:  W | NymeaService: Invalid D-Bus HardwareManager interface.
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1537]:  W | NymeaService: Could not init nymea D-Bus services
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: Starting the network manager.
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: Initializing network manager
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: DBus interface created successfully "/org/freedesktop/NetworkManager"
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: Reading initial properties...
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: Version: "1.14.6"
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: State changed: "NetworkManagerStateConnectedGlobal"
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: Connectivity state changed: "Full"
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: Networking enabled
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: Wireless networking enabled
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: Get available devices
mars 29 11:08:34 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: [+] NetworkDevice("lo" - "Generic", "NetworkDeviceStateUnmanaged")
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: "Livebox-9790" WPA flags: QFlags<WirelessAccessPoint::ApSecurityMode>(ApSecurityModeNone)
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: "Livebox-9790" RSN flags: QFlags<WirelessAccessPoint::ApSecurityMode>(ApSecurityModePairCcmp|ApSecurityModeGroupCcmp|ApSecurityModeKeyMgmtPsk)
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: "Livebox-9790" Capabilities: QFlags<WirelessAccessPoint::ApCapabilities>(ApCapabilitiesPrivacy|ApCapabilitiesWps)
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: "wlan0" [+] AccessPoint(73%, 2.412 GHz, "Livebox-9790", protected)
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: "Livebox-9790" WPA flags: QFlags<WirelessAccessPoint::ApSecurityMode>(ApSecurityModeNone)
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: "Livebox-9790" RSN flags: QFlags<WirelessAccessPoint::ApSecurityMode>(ApSecurityModePairCcmp|ApSecurityModeGroupCcmp|ApSecurityModeKeyMgmtPsk)
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: "Livebox-9790" Capabilities: QFlags<WirelessAccessPoint::ApCapabilities>(ApCapabilitiesPrivacy|ApCapabilitiesWps)
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: "wlan0" [+] AccessPoint(67%, 2.462 GHz, "Livebox-9790", protected)
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: "Livebox-9790" WPA flags: QFlags<WirelessAccessPoint::ApSecurityMode>(ApSecurityModeNone)
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: "Livebox-9790" RSN flags: QFlags<WirelessAccessPoint::ApSecurityMode>(ApSecurityModePairCcmp|ApSecurityModeGroupCcmp|ApSecurityModeKeyMgmtPsk)
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: "Livebox-9790" Capabilities: QFlags<WirelessAccessPoint::ApCapabilities>(ApCapabilitiesPrivacy|ApCapabilitiesWps)
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: "wlan0" [+] AccessPoint(40%, 2.437 GHz, "Livebox-9790", protected)
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: [+] WirelessNetworkDevice("wlan0", "B8:27:EB:03:E9:FE", WirelessNetworkDevice::WirelessModeInfrastructure, 72 [Mb/s], "NetworkDeviceStateActivated")
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: Load connection list
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: Settings: [+] NetworkConnection("Livebox-9790", "{3b0119b3-b1d3-4e68-968a-f1a0cfa600a2}", "", "802-11-wireless", "28.03.2021 19:17")
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: The network manager is now available
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | Application: Networkmanager is now available.
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | Application: Starting the Bluetooth service because of "always" mode.
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  W | NymeaService: Could not enable/disable bluetooth hardware resource. D-Bus interface not available.
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManagerBluetoothServer: -------------------------------------
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManagerBluetoothServer: Starting bluetooth server...
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManagerBluetoothServer: -------------------------------------
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManagerBluetoothServer: Local device "RaspberryPi" "B8:27:EB:FC:16:01"
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  W | qt.bluetooth: Using BlueZ kernel ATT interface
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManagerBluetoothServer: Serial number not specified. Using system uuid from /etc/machine-id as serialnumber.
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManagerBluetoothServer: Create NetworkService.
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManagerBluetoothServer: Create WirelessService.
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManagerBluetoothServer: WirelessService: Using WirelessNetworkDevice("wlan0", "B8:27:EB:03:E9:FE", WirelessNetworkDevice::WirelessModeInfrastructure, 72 [Mb/s], "NetworkDeviceStateActivated")
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManagerBluetoothServer: Start advertising "BT WLAN setup" "B8:27:EB:FC:16:01"
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManagerBluetoothServer: Controller state advertising...
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManagerBluetoothServer: Set running true
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: Network manager initialized successfully.
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: Starting initial wireless network scan...
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManager: Request scan WirelessNetworkDevice("wlan0", "B8:27:EB:03:E9:FE", WirelessNetworkDevice::WirelessModeInfrastructure, 72 [Mb/s], "NetworkDeviceStateActivated")
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | Application: Bluetooth server started
mars 29 11:08:35 RaspberryPi nymea-networkmanager[1537]:  I | NetworkManagerBluetoothServer: Bluetooth host in discoverable mode.



**Let me know, if you find the problem :))) **
I would need to change locations very often with my magic mirror so that's why i would need to connect it to WiFi easily.
@t-mon

**Comment by maxencekyz** [comment]
Any ideas ? :)
@mzanetti @t-mon @nymea-jenkins

**Comment by mzanetti** [comment]
The log looks alright, no errors in there. Did you perhaps deny the permissions to scan Bluetooth to the app? (In Android, the location permission is required to scan for Bluetooth devices)

**Comment by maxencekyz** [comment]
Damn! You were right, the problem came from the location permission on the app !
Problem solved, thanks a lot !!!
Really appreciate your support <3
